version: '3.7'
services:
  api:
    build: ./api
    volumes:
      - ./api:/usr/app
      - /usr/app/node_modules
    ports:
      - '80:8000'
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      PORT: 8000
  www:
    build: ./www
    stdin_open: true
    ports:
      - '3000:3000'
    depends_on:
      - api
    environment:
      NODE_ENV: development
  mongo:
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    image: mongo:4.2.0
