version: '3.7'
services:
  web:
    build: .
    ports:
      - '80:8000'
    restart: always
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      PORT: 8000
  mongo:
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    image: mongo:4.2.0
