version: "3.7"
services:
  api:
    container_name: manga-shelf-api
    build: .
    image: shwilliam/manga-shelf-api
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 3001:3001
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules
  mongo:
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    image: mongo:4.2.0
